/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.univel.trabalho.GUI;

import javax.swing.JOptionPane;
import br.univel.trabalho.Classes.Banco;
import br.univel.trabalho.Classes.Configuracao;
import br.univel.trabalho.Classes.DAO.DAOConfiguracao;

/**
 *
 * @author Cettrans
 */
public class ConfiguracaoGUI extends javax.swing.JDialog {

	/**
	 * Creates new form ConfiguracaoGUI
	 */
	public ConfiguracaoGUI(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();

		if (Banco.verificaConfig()) {

		} else {
			Configuracao c = Banco.getConfiguracao();
			txtnome.setText(c.getNome());
			txttelefone.setText(c.getTelefone());
			txtvlrD.setText(Double.toString(c.getVlrD()));
			txtMulta.setText(Double.toString(c.getMulta()));
			txtvlrL.setText(Double.toString(c.getVlrL()));
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtnome = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txttelefone = new javax.swing.JFormattedTextField();
		jLabel4 = new javax.swing.JLabel();
		txtvlrD = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		txtMulta = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		txtvlrL = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("Nome:");

		jLabel2.setText("Telefone:");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setText("Configuração");

		try {
			txttelefone
					.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
							new javax.swing.text.MaskFormatter("(##)####-####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		jLabel4.setText("Valor Diária:");

		jLabel5.setText("Valor da multa:");

		jLabel6.setText("Valor do Lançamento:");

		jButton1.setText("Salvar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel6)
												.addComponent(jLabel5)
												.addComponent(jLabel4)
												.addComponent(jLabel1)
												.addComponent(jLabel2))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
																.addComponent(
																		txtnome)
																.addComponent(
																		txttelefone,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		132,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																false)
																.addComponent(
																		txtvlrL,
																		javax.swing.GroupLayout.Alignment.LEADING,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		53,
																		Short.MAX_VALUE)
																.addComponent(
																		txtMulta,
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		txtvlrD,
																		javax.swing.GroupLayout.Alignment.LEADING)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(165, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addGap(166,
																		166,
																		166))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jLabel3)
																.addGap(161,
																		161,
																		161)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(7, 7, 7)
								.addComponent(jLabel3)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtnome,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														txttelefone,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														txtvlrD,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														txtMulta,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(
														txtvlrL,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(29, 29, 29).addComponent(jButton1)
								.addContainerGap(49, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		double multa = 0;
		double vd = 0;
		double vl = 0;
		try {
			vd = Double.parseDouble(txtvlrD.getText());
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(rootPane, "Digite apenas números");
			txtvlrD.requestFocus();
			return;
		}

		try {
			multa = Double.parseDouble(txtMulta.getText());
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(rootPane, "Digite apenas números");
			txtMulta.requestFocus();
			return;
		}

		try {
			vl = Double.parseDouble(txtvlrL.getText());
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(rootPane, "Digite apenas números");
			txtvlrL.requestFocus();
			return;
		}
		if (vd < 0 || multa < 0 || vl < 0) {
			JOptionPane.showMessageDialog(rootPane, "Digite valores válidos");
			return;
		}
		DAOConfiguracao.setConfig(txtnome.getText(), txttelefone.getText(), vd,
				multa, vl);
		JOptionPane.showMessageDialog(rootPane, "Configurado com Sucesso!");
		Banco.carregaConfig();
		dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ConfiguracaoGUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ConfiguracaoGUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ConfiguracaoGUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ConfiguracaoGUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ConfiguracaoGUI dialog = new ConfiguracaoGUI(
						new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTextField txtMulta;
	private javax.swing.JTextField txtnome;
	private javax.swing.JFormattedTextField txttelefone;
	private javax.swing.JTextField txtvlrD;
	private javax.swing.JTextField txtvlrL;
	// End of variables declaration//GEN-END:variables
}
