/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.univel.trabalho.GUI;

import java.util.GregorianCalendar;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import br.univel.trabalho.Classes.Banco;
import br.univel.trabalho.Classes.Cliente;
import br.univel.trabalho.Classes.DAO.DAOCliente;

/**
 *
 * @author Cettrans
 */
public class ClienteGUI extends javax.swing.JDialog {

	static TCliente m = new TCliente();
	static Cliente c;

	public ClienteGUI(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		tbC.setModel(m);
		excluir.setEnabled(false);
		alterar.setEnabled(false);
		/*
		 * b.carregaHash(this);
		 */

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtnome = new javax.swing.JTextField();
		txtrua = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tbC = new javax.swing.JTable();
		txtnasc = new javax.swing.JFormattedTextField();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		txtbairro = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		txtnumero = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		txtcep = new javax.swing.JFormattedTextField();
		excluir = new javax.swing.JButton();
		alterar = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();
		txtCidade = new javax.swing.JTextField();
		jLabel10 = new javax.swing.JLabel();
		txtEstado = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setText("Nome:");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel2.setText("Endereço");

		jLabel3.setText("Data de Nascimento:");

		jButton1.setText("Cadastrar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		tbC.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {
				{ null, null, null, null }, { null, null, null, null },
				{ null, null, null, null }, { null, null, null, null } },
				new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		tbC.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tbCMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tbC);

		try {
			txtnasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
					new javax.swing.text.MaskFormatter("##/##/####")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		jLabel4.setText("Rua:");

		jLabel5.setText("Bairro:");

		jLabel6.setText("CEP:");

		jLabel7.setText("Número:");

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel8.setText("Cliente");

		try {
			txtcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
					new javax.swing.text.MaskFormatter("##.###-###")));
		} catch (java.text.ParseException ex) {
			ex.printStackTrace();
		}

		excluir.setText("Excluir");
		excluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				excluirActionPerformed(evt);
			}
		});

		alterar.setText("Alterar");
		alterar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				alterarActionPerformed(evt);
			}
		});

		jLabel9.setText("Cidade:");

		jLabel10.setText("Estado:");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 473,
						Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(30, 30,
																		30)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(75,
																										75,
																										75)
																								.addComponent(
																										jButton1)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										alterar)
																								.addGap(23,
																										23,
																										23)
																								.addComponent(
																										excluir))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(9,
																										9,
																										9)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGap(8,
																																		8,
																																		8)
																																.addComponent(
																																		jLabel6)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addComponent(
																																		txtcep,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		85,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.TRAILING)
																																				.addComponent(
																																						jLabel1)
																																				.addComponent(
																																						jLabel5)
																																				.addComponent(
																																						jLabel4))
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addGroup(
																																		layout.createParallelGroup(
																																				javax.swing.GroupLayout.Alignment.LEADING)
																																				.addComponent(
																																						txtnome,
																																						javax.swing.GroupLayout.PREFERRED_SIZE,
																																						322,
																																						javax.swing.GroupLayout.PREFERRED_SIZE)
																																				.addGroup(
																																						layout.createSequentialGroup()
																																								.addGroup(
																																										layout.createParallelGroup(
																																												javax.swing.GroupLayout.Alignment.TRAILING,
																																												false)
																																												.addComponent(
																																														txtbairro,
																																														javax.swing.GroupLayout.Alignment.LEADING)
																																												.addComponent(
																																														txtrua,
																																														javax.swing.GroupLayout.Alignment.LEADING,
																																														javax.swing.GroupLayout.DEFAULT_SIZE,
																																														210,
																																														Short.MAX_VALUE))
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																								.addComponent(
																																										jLabel7)
																																								.addPreferredGap(
																																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																								.addComponent(
																																										txtnumero,
																																										javax.swing.GroupLayout.PREFERRED_SIZE,
																																										49,
																																										javax.swing.GroupLayout.PREFERRED_SIZE))))))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																												.addGroup(
																														javax.swing.GroupLayout.Alignment.LEADING,
																														layout.createSequentialGroup()
																																.addGap(3,
																																		3,
																																		3)
																																.addComponent(
																																		jLabel9)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																.addComponent(
																																		txtCidade))
																												.addGroup(
																														javax.swing.GroupLayout.Alignment.LEADING,
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel3)
																																.addGap(29,
																																		29,
																																		29)
																																.addComponent(
																																		txtnasc,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		86,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										jLabel10)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										txtEstado,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										152,
																										javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(169,
																		169,
																		169)
																.addComponent(
																		jLabel2))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(198,
																		198,
																		198)
																.addComponent(
																		jLabel8)))
								.addContainerGap(25, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jLabel8)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtnome,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														txtrua,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7)
												.addComponent(
														txtnumero,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														txtbairro,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(8, 8, 8)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jLabel10)
																.addComponent(
																		txtEstado,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jLabel9)
																.addComponent(
																		txtCidade,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(
														txtcep,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														txtnasc,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(15, 15, 15)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(excluir)
												.addComponent(alterar))
								.addGap(18, 18, 18)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										227,
										javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		int numero;
		/*
		 * Verifica se tem campos em branco
		 */
		if (txtCidade.getText().equals("") || txtEstado.getText().equals("")
				|| txtbairro.getText().equals("")
				|| txtrua.getText().equals("") || txtnome.getText().equals("")
				|| txtnumero.getText().equals("")
				|| txtnasc.getText().equals("  /  /    ")
				|| txtcep.getText().equals("  .   -   ")) {
			JOptionPane.showMessageDialog(rootPane, "Existem campos em branco");
			return;
		}
		try {
			numero = Integer.parseInt(txtnumero.getText());
			if (numero < 0) {
				JOptionPane.showMessageDialog(rootPane,
						"Digite um valor válido");
				txtnumero.requestFocus();
				return;
			}
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(rootPane, "Digite um valor válido");
			txtnumero.requestFocus();
			return;
		}

		if (!DAOCliente.verificaData(txtnasc.getText())) {
			JOptionPane.showMessageDialog(rootPane, "Digite uma data válida");
			txtnasc.requestFocus();
			return;
		}

		DAOCliente.setCliente(txtnome.getText(), txtrua.getText(),
				txtbairro.getText(), txtCidade.getText(), txtEstado.getText(),
				txtcep.getText(), numero, txtnasc.getText());

		JOptionPane.showMessageDialog(rootPane,
				"Cliente Cadastrado com Sucesso");
		txtnome.setText("");
		txtbairro.setText("");
		txtcep.setText("");
		txtnasc.setText("");
		txtnumero.setText("");
		txtrua.setText("");
		txtCidade.setText("");
		txtEstado.setText("");
		m.fireTableDataChanged();

	}// GEN-LAST:event_jButton1ActionPerformed

	private void tbCMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tbCMouseClicked
		excluir.setEnabled(true);
		alterar.setEnabled(true);
		c = DAOCliente.getCliente(tbC.getSelectedRow());
		txtnome.setText(c.getNome());
		txtbairro.setText(c.getEndereco().getBairro());
		txtcep.setText(c.getEndereco().getCep());
		txtrua.setText(c.getEndereco().getRua());
		txtCidade.setText(c.getEndereco().getCidade());
		txtEstado.setText(c.getEndereco().getEstado());

		txtnasc.setText(Banco.getDataString(c.getNasc()));
		txtnumero.setText(Integer.toString(c.getEndereco().getNumero()));
	}// GEN-LAST:event_tbCMouseClicked

	private void excluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_excluirActionPerformed
		Cliente c = DAOCliente.getCliente(tbC.getSelectedRow());
		int i;
		if (Banco.verificaCliente(c)) {
			JOptionPane
					.showMessageDialog(rootPane,
							"Não é possível exlcuir um Cliente que está em uma locação Ativa");
			i = 2;
		} else
			i = JOptionPane.showConfirmDialog(rootPane,
					"Deseja realmente excluir" + " '" + c.getNome() + "' ?");
		switch (i) {
		case 0: {
			DAOCliente.deleteCliente(c);
			m.fireTableDataChanged();
			excluir.setEnabled(false);
			alterar.setEnabled(false);
			JOptionPane.showMessageDialog(rootPane,
					"Cliente excluído com Sucesso!");
			txtnome.setText("");
			txtbairro.setText("");
			txtcep.setText("");
			txtnasc.setText("");
			txtnumero.setText("");
			txtrua.setText("");
			txtCidade.setText("");
			txtEstado.setText("");
			return;
		}
		case 1: {
			alterar.setEnabled(false);
			excluir.setEnabled(false);
			return;
		}
		default: {
			alterar.setEnabled(false);
			excluir.setEnabled(false);
			return;
		}

		}
	}// GEN-LAST:event_excluirActionPerformed

	private void alterarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_alterarActionPerformed
		if (c == null) {
			JOptionPane.showMessageDialog(rootPane, "Selecione um Cliente");
			return;
		} else {
			int numero;
			try {
				if (txtCidade.getText().equals("")
						|| txtEstado.getText().equals("")
						|| txtbairro.getText().equals("")
						|| txtrua.getText().equals("")
						|| txtnome.getText().equals("")
						|| txtnumero.getText().equals("")
						|| txtnasc.getText().equals("  /  /    ")
						|| txtcep.getText().equals("  .   -   ")) {
					JOptionPane.showMessageDialog(rootPane,
							"Existem campos em branco");
					return;
				}

				numero = Integer.parseInt(txtnumero.getText());
				if (numero < 0) {
					JOptionPane.showMessageDialog(rootPane,
							"Digite um valor válido");
					txtnumero.requestFocus();
					return;
				}
			} catch (NumberFormatException e) {
				JOptionPane.showMessageDialog(rootPane,
						"Digite um valor válido");
				txtnumero.requestFocus();
				return;
			}
			int i = JOptionPane.showConfirmDialog(rootPane,
					"Deseja realmente alterar" + " '" + c.getNome() + "' ?");
			switch (i) {
			case 0: {
				DAOCliente.updateCliente(txtnome.getText(), txtrua.getText(),
						txtbairro.getText(), txtCidade.getText(),
						txtEstado.getText(), txtcep.getText(), numero,
						txtnasc.getText(), c);

				JOptionPane.showMessageDialog(rootPane,
						"Cliente Alterado com Sucesso");
				alterar.setEnabled(false);
				excluir.setEnabled(false);
				m.fireTableDataChanged();
				txtnome.setText("");
				txtbairro.setText("");
				txtcep.setText("");
				txtnasc.setText("");
				txtnumero.setText("");
				txtCidade.setText("");
				txtEstado.setText("");
				txtrua.setText("");
				return;
			}
			case 1: {
				alterar.setEnabled(false);
				excluir.setEnabled(false);
				return;
			}
			default: {
				txtnome.setText("");
				txtbairro.setText("");
				txtcep.setText("");
				txtnasc.setText("");
				txtnumero.setText("");
				txtrua.setText("");
				txtCidade.setText("");
				txtEstado.setText("");
				alterar.setEnabled(false);
				excluir.setEnabled(false);
				return;
			}
			}
		}

	}// GEN-LAST:event_alterarActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ClienteGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				ClienteGUI dialog = new ClienteGUI(new javax.swing.JFrame(),
						true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton alterar;
	private javax.swing.JButton excluir;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tbC;
	private javax.swing.JTextField txtCidade;
	private javax.swing.JTextField txtEstado;
	private javax.swing.JTextField txtbairro;
	private javax.swing.JFormattedTextField txtcep;
	private javax.swing.JFormattedTextField txtnasc;
	private javax.swing.JTextField txtnome;
	private javax.swing.JTextField txtnumero;
	private javax.swing.JTextField txtrua;
	// End of variables declaration//GEN-END:variables
}

class TCliente extends AbstractTableModel {

	@Override
	public int getRowCount() {
		return Banco.getHash("Cliente").size();
	}

	@Override
	public int getColumnCount() {
		return 3;
	}

	public String getColumnName(int i) {
		switch (i) {
		case 0:
			return "ID";
		case 1:
			return "Nome";
		default:
			return "Nascimento";
		}
	}

	@Override
	public Object getValueAt(int rowIndex, int columnIndex) {
		Cliente c = DAOCliente.getCliente(rowIndex);

		switch (columnIndex) {
		case 0:
			return c.getId();
		case 1:
			return c.getNome();
		default:
			return c.getNasc().get(5) + "/" + (c.getNasc().get(2) + 1) + "/"
					+ c.getNasc().get(1);

		}

	}

}
