/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.univel.trabalho.GUI;

import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import br.univel.trabalho.Classes.Banco;
import br.univel.trabalho.Classes.DAO.DAOGenero;
import br.univel.trabalho.Classes.Genero;

/**
 *
 * @author Cettrans
 */
public class GeneroGUI extends javax.swing.JDialog {

	TGenero tg = new TGenero();
	Genero g;

	public GeneroGUI(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		Banco b = Banco.getBanco();
		tbGenero.setModel(tg);
		alterar.setEnabled(false);
		excluir.setEnabled(false);
		/*
		 * b.carregaHash(this);
		 */

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtnome = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		tbGenero = new javax.swing.JTable();
		alterar = new javax.swing.JButton();
		excluir = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel1.setText("Gênero");

		jLabel2.setText("Nome:");

		jButton1.setText("Salvar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		tbGenero.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		tbGenero.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				tbGeneroMouseClicked(evt);
			}
		});
		jScrollPane1.setViewportView(tbGenero);

		alterar.setText("Alterar");
		alterar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				alterarActionPerformed(evt);
			}
		});

		excluir.setText("Excluir");
		excluir.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				excluirActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										345,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(0, 0, Short.MAX_VALUE))
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(41, 41,
																		41)
																.addComponent(
																		jLabel2)
																.addGap(32, 32,
																		32)
																.addComponent(
																		txtnome,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		127,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(141,
																		141,
																		141)
																.addComponent(
																		jLabel1))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(76, 76,
																		76)
																.addComponent(
																		jButton1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		alterar)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		excluir)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jLabel1)
								.addGap(23, 23, 23)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														txtnome,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(23, 23, 23)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(alterar)
												.addComponent(excluir))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										284,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		if (txtnome.getText().equals("")) {
			JOptionPane.showMessageDialog(rootPane, "Existem campos em branco");
			return;
		}
		DAOGenero.setGenero(txtnome.getText());
		JOptionPane.showMessageDialog(rootPane,
				"Gênero Cadastrado com Sucesso.");
		txtnome.setText("");
		tg.fireTableDataChanged();

	}// GEN-LAST:event_jButton1ActionPerformed

	private void alterarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_alterarActionPerformed
		if (g == null) {
			JOptionPane.showMessageDialog(rootPane, "Selecione um Genero");
			return;
		} else {
			int i = JOptionPane.showConfirmDialog(rootPane,
					"Deseja realmente alterar" + " '" + g.getNome() + "' ?");
			switch (i) {
			case 0: {
				if (txtnome.getText().equals("")) {
					JOptionPane.showMessageDialog(rootPane,
							"Existem campos em branco");
					return;
				}
				DAOGenero.updateGenero(txtnome.getText(), g);
				JOptionPane.showMessageDialog(rootPane,
						"Genero Alterado com Sucesso");
				alterar.setEnabled(false);
				excluir.setEnabled(false);
				tg.fireTableDataChanged();
				txtnome.setText("");
				return;
			}
			case 1: {
				alterar.setEnabled(false);
				excluir.setEnabled(false);
				return;
			}
			default: {
				txtnome.setText("");
				alterar.setEnabled(false);
				excluir.setEnabled(false);
				return;
			}
			}
		}
	}// GEN-LAST:event_alterarActionPerformed

	private void excluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_excluirActionPerformed
		Genero g = DAOGenero.getGenero(tbGenero.getSelectedRow());
		int i = JOptionPane.showConfirmDialog(rootPane,
				"Deseja realmente excluir" + " '" + g.getNome() + " ' ?");
		switch (i) {
		case 0: {
			DAOGenero.deleteGenero(g);
			tg.fireTableDataChanged();
			excluir.setEnabled(false);
			alterar.setEnabled(false);
			txtnome.setText("");
			JOptionPane.showMessageDialog(rootPane,
					"Gênero excluído com sucesso!");
			return;
		}
		case 1: {
			JOptionPane.showMessageDialog(rootPane,
					"Gênero não foi excluído");
			alterar.setEnabled(false);
			excluir.setEnabled(false);
			return;
		}
		default: {
			alterar.setEnabled(false);
			excluir.setEnabled(false);
			return;
		}
		}
	}// GEN-LAST:event_excluirActionPerformed

	private void tbGeneroMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tbGeneroMouseClicked
		excluir.setEnabled(true);
		alterar.setEnabled(true);
		g = DAOGenero.getGenero(tbGenero.getSelectedRow());
		txtnome.setText(g.getNome());
	}// GEN-LAST:event_tbGeneroMouseClicked

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GeneroGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GeneroGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GeneroGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GeneroGUI.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				GeneroGUI dialog = new GeneroGUI(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton alterar;
	private javax.swing.JButton excluir;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tbGenero;
	private javax.swing.JTextField txtnome;
	// End of variables declaration//GEN-END:variables
}

class TGenero extends AbstractTableModel {

	@Override
	public int getRowCount() {
		return Banco.getHash("Genero").size();
	}

	@Override
	public int getColumnCount() {
		return 1;
	}

	public String getColumnName(int i) {
		switch (i) {
		default:
			return "Nome";
		}
	}

	@Override
	public Object getValueAt(int rowIndex, int columnIndex) {
		Set s = Banco.getHash("Genero").keySet();
		Object o[] = s.toArray();
		Genero g = (Genero) Banco.getHash("Genero").get(o[rowIndex]);
		switch (columnIndex) {
		default:
			return g.getNome();

		}
	}

}