/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.univel.trabalho;

import javax.swing.JOptionPane;
import br.univel.trabalho.Classes.Banco;
import br.univel.trabalho.Classes.Configuracao;
import br.univel.trabalho.Classes.DAO.DAOConfiguracao;
import br.univel.trabalho.GUI.ClienteGUI;
import br.univel.trabalho.GUI.ConfiguracaoGUI;
import br.univel.trabalho.GUI.FilmeGUI;
import br.univel.trabalho.GUI.GeneroGUI;
import br.univel.trabalho.GUI.LocacaoGUI;
import br.univel.trabalho.GUI.RelatorioGUI;
import br.univel.trabalho.GUI.RelatorioPerdidosGUI;
import br.univel.trabalho.GUI.RelatorioSemanalGUI;

/**
 *
 * @author Cettrans
 */
public class Principal extends javax.swing.JFrame {

	public Principal() {
		initComponents();
		Banco.loadBanco();

		if (Banco.verificaConfig()) {
			ConfiguracaoGUI c = new ConfiguracaoGUI(this,
					rootPaneCheckingEnabled);
			JOptionPane.showMessageDialog(null,
					"Antes de Iniciar o Programa, Configure sua Locadora");
			c.setVisible(true);

		}

		nome.setText(DAOConfiguracao.getNome());
		telefone.setText(DAOConfiguracao.getFone());

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jMenuItem2 = new javax.swing.JMenuItem();
		jMenuBar2 = new javax.swing.JMenuBar();
		jMenu4 = new javax.swing.JMenu();
		jMenu5 = new javax.swing.JMenu();
		jMenuBar3 = new javax.swing.JMenuBar();
		jMenu6 = new javax.swing.JMenu();
		jMenu7 = new javax.swing.JMenu();
		jMenuBar4 = new javax.swing.JMenuBar();
		jMenu8 = new javax.swing.JMenu();
		jMenu9 = new javax.swing.JMenu();
		nome = new javax.swing.JLabel();
		telefone = new javax.swing.JLabel();
		jMenuBar5 = new javax.swing.JMenuBar();
		jMenu10 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();
		jMenuItem4 = new javax.swing.JMenuItem();
		jMenuItem5 = new javax.swing.JMenuItem();
		jMenuItem6 = new javax.swing.JMenuItem();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem7 = new javax.swing.JMenuItem();
		jMenuItem8 = new javax.swing.JMenuItem();
		jMenuItem9 = new javax.swing.JMenuItem();

		jMenuItem1.setText("jMenuItem1");

		jMenu3.setText("jMenu3");

		jMenuItem2.setText("jMenuItem2");

		jMenu4.setText("File");
		jMenuBar2.add(jMenu4);

		jMenu5.setText("Edit");
		jMenuBar2.add(jMenu5);

		jMenu6.setText("File");
		jMenuBar3.add(jMenu6);

		jMenu7.setText("Edit");
		jMenuBar3.add(jMenu7);

		jMenu8.setText("File");
		jMenuBar4.add(jMenu8);

		jMenu9.setText("Edit");
		jMenuBar4.add(jMenu9);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		nome.setText("null");

		telefone.setText("null");

		jMenu10.setText("Gerenciador");

		jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/br/univel/trabalho/Icons/Client.png"))); // NOI18N
		jMenuItem3.setText("Cliente");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu10.add(jMenuItem3);

		jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/br/univel/trabalho/Icons/film.png"))); // NOI18N
		jMenuItem4.setText("Filme");
		jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem4ActionPerformed(evt);
			}
		});
		jMenu10.add(jMenuItem4);

		jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/br/univel/trabalho/Icons/genre.png"))); // NOI18N
		jMenuItem5.setText("Gênero");
		jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem5ActionPerformed(evt);
			}
		});
		jMenu10.add(jMenuItem5);

		jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/br/univel/trabalho/Icons/Locacao.png"))); // NOI18N
		jMenuItem6.setText("Locação");
		jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem6ActionPerformed(evt);
			}
		});
		jMenu10.add(jMenuItem6);

		jMenuBar5.add(jMenu10);

		jMenu1.setText("Configurações");
		jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jMenu1MouseClicked(evt);
			}
		});
		jMenuBar5.add(jMenu1);

		jMenu2.setText("Relatórios");

		jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/br/univel/trabalho/Icons/report.png"))); // NOI18N
		jMenuItem7.setText("Pesquisar Relatório");
		jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem7ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem7);

		jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/br/univel/trabalho/Icons/report.png"))); // NOI18N
		jMenuItem8.setText("Relatório Semanal");
		jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem8ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem8);

		jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/br/univel/trabalho/Icons/report.png"))); // NOI18N
		jMenuItem9.setText("Relatório de Perdidos");
		jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem9ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem9);

		jMenuBar5.add(jMenu2);

		setJMenuBar(jMenuBar5);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(163, 163, 163)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(telefone)
												.addComponent(nome))
								.addContainerGap(221, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(nome)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(telefone)
								.addContainerGap(229, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
		ClienteGUI c = new ClienteGUI(this, rootPaneCheckingEnabled);
		c.setVisible(true);
	}// GEN-LAST:event_jMenuItem3ActionPerformed

	private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem4ActionPerformed
		FilmeGUI f = new FilmeGUI(this, rootPaneCheckingEnabled);
		f.setVisible(true);
	}// GEN-LAST:event_jMenuItem4ActionPerformed

	private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem5ActionPerformed
		GeneroGUI a = new GeneroGUI(this, rootPaneCheckingEnabled);
		a.setVisible(true);
	}// GEN-LAST:event_jMenuItem5ActionPerformed

	private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem6ActionPerformed
		LocacaoGUI l = new LocacaoGUI(this, rootPaneCheckingEnabled);
		l.setVisible(true);
	}// GEN-LAST:event_jMenuItem6ActionPerformed

	private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jMenu1MouseClicked
		ConfiguracaoGUI c = new ConfiguracaoGUI(this, rootPaneCheckingEnabled);
		c.setVisible(true);
	}// GEN-LAST:event_jMenu1MouseClicked

	private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem7ActionPerformed
		RelatorioGUI r = new RelatorioGUI(this, rootPaneCheckingEnabled);
		r.setVisible(true);
	}// GEN-LAST:event_jMenuItem7ActionPerformed

	private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem8ActionPerformed
		RelatorioSemanalGUI r = new RelatorioSemanalGUI(this,
				rootPaneCheckingEnabled);
		r.setVisible(true);
	}// GEN-LAST:event_jMenuItem8ActionPerformed

	private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem9ActionPerformed
		RelatorioPerdidosGUI r = new RelatorioPerdidosGUI(this,
				rootPaneCheckingEnabled);
		r.setVisible(true);
	}// GEN-LAST:event_jMenuItem9ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Principal.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Principal().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu10;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenu jMenu5;
	private javax.swing.JMenu jMenu6;
	private javax.swing.JMenu jMenu7;
	private javax.swing.JMenu jMenu8;
	private javax.swing.JMenu jMenu9;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JMenuBar jMenuBar3;
	private javax.swing.JMenuBar jMenuBar4;
	private javax.swing.JMenuBar jMenuBar5;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem2;
	private javax.swing.JMenuItem jMenuItem3;
	private javax.swing.JMenuItem jMenuItem4;
	private javax.swing.JMenuItem jMenuItem5;
	private javax.swing.JMenuItem jMenuItem6;
	private javax.swing.JMenuItem jMenuItem7;
	private javax.swing.JMenuItem jMenuItem8;
	private javax.swing.JMenuItem jMenuItem9;
	public static javax.swing.JLabel nome;
	public static javax.swing.JLabel telefone;
	// End of variables declaration//GEN-END:variables
}
